name: tck
on: 
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Java 20
      uses: actions/setup-java@v1
      with:
        java-version: 20
    - name: Build with Maven
      run: mvn -B --ntp package
    - name: Run TCK
      run: mvn -B -DskipTests=true -DskipITs=true -ntp -P tck verify
